language: node_js
sudo: true
node_js:
- 8
install:
- echo "Entering install stage ..."
- sudo docker-compose -f docker-compose-ci.yml up --build -d
script:
- echo "Entering execution stage ..."
- sudo docker-compose down --rmi all -v