language: node_js

sudo: true

node_js:
- 8.12

services:
- docker

install:
- echo Entering install stage ...
- echo $DOCKER_USERNAME
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- cp .sample.env .env

script:
- echo Entering execution stage ...
- sudo docker build -t $REPOSITORY_URI:latest -f Dockerfile-ci .
- sudo docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$TRAVIS_COMMIT
- echo Pushing the Docker images ...
- sudo docker push $REPOSITORY_URI:latest
- sudo docker push $REPOSITORY_URI:$TRAVIS_COMMIT