version: '3'
services:
  api:
    container_name: instagram_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
    - "10000:3000"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    env_file:
    - .env
