version: '3'
services:
  api:
    container_name: instagram_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
    - "10000:3000"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    env_file:
    - .env
    depends_on:
    - redis
  redis:
    container_name: instagram_api_redis
    image: redis:5-alpine
    command: redis-server --requirepass 12345678
    ports:
    - "6379:6379"
